In [1]:
import numpy as np

M = 10  # Number of rows
N = 20  # Number of columns

# Create a NumPy array filled with random integers between 1 and 100
table = np.random.randint(1, 101, size=(M, N))

# Print the table
print(table)


[[ 83  93  53  35  13  20  98   1  84  42  71  95  51  77  89 100   4  21
   97  38]
 [ 21  29  91  96   9  89   3  61   4   9  81  53  68  39  97  18  77  37
   49  41]
 [ 80  16  30  98  10  85   7  15  89  60  61  88  86  86  16  86  33  35
   33  98]
 [ 74  33  87  20  33  65  61  17  13   4  28  92  40  97  78  89  89   4
   42  55]
 [ 74  55  10  40  39  96  26  97  47  13  20  65  29  59  85  10  49   8
   57  91]
 [  6  41  91  70   7  89  77   8  13  19  66  43  71  80  40  44  14  53
   57  29]
 [100  73  43  13  22   8  91  35  79  99  97  90  62  31  37  81  56  48
   84  60]
 [ 40  89  28  47  26  80  67  49  10   8  40  47  85  35  40  16  25  82
   32  49]
 [ 55  33   6  20  42  38  90  86  94  71  16   9  11  84  96  72  58  58
   60  96]
 [ 19  70  60  97  36  25  37  99  56  55  77  95  24  77  54  36  70  15
   30  52]]


In [2]:
# Assuming you have already created the 'table' using the code provided earlier

third_row = table[2]  # Index 2 corresponds to the third row (Python uses 0-based indexing)

print("Third row using Python list:")
print(third_row)


Third row using Python list:
[80 16 30 98 10 85  7 15 89 60 61 88 86 86 16 86 33 35 33 98]


In [3]:
import numpy as np

# Assuming you have already created the 'table' using the NumPy code provided earlier

third_row = table[2, :]  # Index 2 corresponds to the third row, ':' means all columns

print("Third row using NumPy:")
print(third_row)


Third row using NumPy:
[80 16 30 98 10 85  7 15 89 60 61 88 86 86 16 86 33 35 33 98]


In [4]:
# Assuming you have already created the 'table' using the code provided earlier

third_column = [row[2] for row in table]  # Index 2 corresponds to the third column

print("Third column using Python list:")
for value in third_column:
    print(value)


Third column using Python list:
53
91
30
87
10
91
43
28
6
60


In [5]:
import numpy as np

# Assuming you have already created the 'table' using the NumPy code provided earlier

third_column = table[:, 2]  # Index 2 corresponds to the third column

print("Third column using NumPy:")
print(third_column)


Third column using NumPy:
[53 91 30 87 10 91 43 28  6 60]


In [6]:
# Assuming you have already created the 'table' using the code provided earlier

last_row_index = len(table) - 1  # Index of the last row

for i in range(len(table[last_row_index])):
    table[last_row_index][i] = 7

print("Table with last row elements set to 7 using Python list:")
for row in table:
    print(row)


Table with last row elements set to 7 using Python list:
[ 83  93  53  35  13  20  98   1  84  42  71  95  51  77  89 100   4  21
  97  38]
[21 29 91 96  9 89  3 61  4  9 81 53 68 39 97 18 77 37 49 41]
[80 16 30 98 10 85  7 15 89 60 61 88 86 86 16 86 33 35 33 98]
[74 33 87 20 33 65 61 17 13  4 28 92 40 97 78 89 89  4 42 55]
[74 55 10 40 39 96 26 97 47 13 20 65 29 59 85 10 49  8 57 91]
[ 6 41 91 70  7 89 77  8 13 19 66 43 71 80 40 44 14 53 57 29]
[100  73  43  13  22   8  91  35  79  99  97  90  62  31  37  81  56  48
  84  60]
[40 89 28 47 26 80 67 49 10  8 40 47 85 35 40 16 25 82 32 49]
[55 33  6 20 42 38 90 86 94 71 16  9 11 84 96 72 58 58 60 96]
[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]


In [7]:
import numpy as np

# Assuming you have already created the 'table' using the NumPy code provided earlier

last_row_index = table.shape[0] - 1  # Index of the last row

table[last_row_index, :] = 7

print("Table with last row elements set to 7 using NumPy:")
print(table)


Table with last row elements set to 7 using NumPy:
[[ 83  93  53  35  13  20  98   1  84  42  71  95  51  77  89 100   4  21
   97  38]
 [ 21  29  91  96   9  89   3  61   4   9  81  53  68  39  97  18  77  37
   49  41]
 [ 80  16  30  98  10  85   7  15  89  60  61  88  86  86  16  86  33  35
   33  98]
 [ 74  33  87  20  33  65  61  17  13   4  28  92  40  97  78  89  89   4
   42  55]
 [ 74  55  10  40  39  96  26  97  47  13  20  65  29  59  85  10  49   8
   57  91]
 [  6  41  91  70   7  89  77   8  13  19  66  43  71  80  40  44  14  53
   57  29]
 [100  73  43  13  22   8  91  35  79  99  97  90  62  31  37  81  56  48
   84  60]
 [ 40  89  28  47  26  80  67  49  10   8  40  47  85  35  40  16  25  82
   32  49]
 [ 55  33   6  20  42  38  90  86  94  71  16   9  11  84  96  72  58  58
   60  96]
 [  7   7   7   7   7   7   7   7   7   7   7   7   7   7   7   7   7   7
    7   7]]


In [8]:
# Assuming you have already created the 'table' using the code provided earlier

for i in range(len(table)):
    table[i][-1] = table[i][0] + table[i][1]

print("Table with last column set to sum of first two columns using Python list:")
for row in table:
    print(row)


Table with last column set to sum of first two columns using Python list:
[ 83  93  53  35  13  20  98   1  84  42  71  95  51  77  89 100   4  21
  97 176]
[21 29 91 96  9 89  3 61  4  9 81 53 68 39 97 18 77 37 49 50]
[80 16 30 98 10 85  7 15 89 60 61 88 86 86 16 86 33 35 33 96]
[ 74  33  87  20  33  65  61  17  13   4  28  92  40  97  78  89  89   4
  42 107]
[ 74  55  10  40  39  96  26  97  47  13  20  65  29  59  85  10  49   8
  57 129]
[ 6 41 91 70  7 89 77  8 13 19 66 43 71 80 40 44 14 53 57 47]
[100  73  43  13  22   8  91  35  79  99  97  90  62  31  37  81  56  48
  84 173]
[ 40  89  28  47  26  80  67  49  10   8  40  47  85  35  40  16  25  82
  32 129]
[55 33  6 20 42 38 90 86 94 71 16  9 11 84 96 72 58 58 60 88]
[ 7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7 14]


In [9]:
import numpy as np

# Assuming you have already created the 'table' using the NumPy code provided earlier

table[:, -1] = table[:, 0] + table[:, 1]

print("Table with last column set to sum of first two columns using NumPy:")
print(table)


Table with last column set to sum of first two columns using NumPy:
[[ 83  93  53  35  13  20  98   1  84  42  71  95  51  77  89 100   4  21
   97 176]
 [ 21  29  91  96   9  89   3  61   4   9  81  53  68  39  97  18  77  37
   49  50]
 [ 80  16  30  98  10  85   7  15  89  60  61  88  86  86  16  86  33  35
   33  96]
 [ 74  33  87  20  33  65  61  17  13   4  28  92  40  97  78  89  89   4
   42 107]
 [ 74  55  10  40  39  96  26  97  47  13  20  65  29  59  85  10  49   8
   57 129]
 [  6  41  91  70   7  89  77   8  13  19  66  43  71  80  40  44  14  53
   57  47]
 [100  73  43  13  22   8  91  35  79  99  97  90  62  31  37  81  56  48
   84 173]
 [ 40  89  28  47  26  80  67  49  10   8  40  47  85  35  40  16  25  82
   32 129]
 [ 55  33   6  20  42  38  90  86  94  71  16   9  11  84  96  72  58  58
   60  88]
 [  7   7   7   7   7   7   7   7   7   7   7   7   7   7   7   7   7   7
    7  14]]
