In [1]:
import numpy as np

# Create a random NumPy array with shape (5, 6) filled with integers between 1 and 100
array = np.random.randint(1, 101, size=(5, 6))

print("Random NumPy Array:")
print(array)

# Compute the maximum integer for each row
max_per_row = np.max(array, axis=1)

print("Maximum integer for each row:")
print(max_per_row)


Random NumPy Array:
[[22  7 47 53 60 55]
 [54 48 67 90  2 60]
 [83 68 67 93 71 15]
 [82 50  4  5 28 37]
 [38 58 60 26 67 30]]
Maximum integer for each row:
[60 90 93 82 67]
